<?php

namespace Tests\Unit;

use App\Models\Category;
use Tests\TestCase;

class CategoryTest extends TestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_create()
    {

        $data = [
            'name' => 'Test Category',
            'description' => 'Unit Testing Categories'];
        $category = Category::create($data);

        $this->assertDatabaseHas('categories', [
            'id' => $category->id,
            'name' => 'Test Category',
            'description' =>'Unit Testing Categories',
        ]);
    }
}
